### ISSUE TITLE
Bubbles (\infommmarginnotes) still have Sans Serif font.

### ISSUE THREAD

**Issue by rodrigolece** [oliversheridanmethven/lay_report#4]
The title says it all. I understand that you wanted to get rid of Sans Serif completely but this is the  last place where I can still find a different text.

**Comment by rodrigolece** [comment]
By the way, amazing job! Really easy to use and lots of useful features (`\todo` is absolutely amazing).

**Comment by oliversheridanmethven** [comment]
## This is intentional

The margin font is intended to be sans serif to make it stand out from the main body. 

## Compare:

### Original word version
![image](https://user-images.githubusercontent.com/13259221/45152811-fc0c2f80-b1c9-11e8-8f11-02866accc122.png)

### Latex version
![image](https://user-images.githubusercontent.com/13259221/45152887-35449f80-b1ca-11e8-943c-faa2e6599292.png)

The nice advantage of the new style is that if you want to include maths in a side bubble it will use the sans serif maths font too:
![image](https://user-images.githubusercontent.com/13259221/45152956-60c78a00-b1ca-11e8-987d-dc48b035df36.png)



PS - `todo` is among several great packages loaded inside the preamble. Well worth a look.
